/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hr.kbratko.ui.view;

import hr.kbratko.bll.base.manager.model.PersonDomainModelManager;
import hr.kbratko.bll.concrete.factory.PersonDomainModelManagerFactory;
import hr.kbratko.bll.concrete.model.PersonDomainModel;
import hr.kbratko.bll.concrete.model.UserDomainModel;
import hr.kbratko.lib.ui.Borders;
import hr.kbratko.lib.ui.Messages;
import hr.kbratko.ui.base.view.BaseUserView;
import hr.kbratko.ui.base.view.CardContainer;
import hr.kbratko.ui.view.model.PersonTableModel;
import java.awt.Dimension;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.Optional;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author kbratko
 */
public class PersonCRUDView
  extends BaseUserView {

  private final PersonDomainModelManager _personManager =
                                         PersonDomainModelManagerFactory
                                           .getManager();

  private final Collection<JTextField> _validationFields;

  private Optional<PersonDomainModel> _selectedPerson = Optional.empty();

//  private BaseTableModel
  /**
   * Creates new form PersonCRUDView
   *
   * @param loggedInUser
   * @param cardContainer
   */
  public PersonCRUDView(UserDomainModel loggedInUser,
                        CardContainer cardContainer) {
    super(loggedInUser, cardContainer);
    initComponents();

    this._validationFields = Arrays.asList(tfFName, tfLName);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    lblFName = new javax.swing.JLabel();
    tfFName = new javax.swing.JTextField();
    lblLName = new javax.swing.JLabel();
    tfLName = new javax.swing.JTextField();
    btnDelete = new javax.swing.JButton();
    btnCreate = new javax.swing.JButton();
    btnUpdate = new javax.swing.JButton();
    spTblPeople = new javax.swing.JScrollPane();
    tblPeople = new javax.swing.JTable();

    setBackground(new java.awt.Color(255, 255, 255));
    setPreferredSize(new java.awt.Dimension(1280, 620));
    addComponentListener(new java.awt.event.ComponentAdapter() {
      public void componentShown(java.awt.event.ComponentEvent evt) {
        formComponentShown(evt);
      }
    });

    lblFName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    lblFName.setText("First name:");

    tfFName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

    lblLName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    lblLName.setText("Last name:");

    tfLName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

    btnDelete.setBackground(new java.awt.Color(255, 102, 102));
    btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    btnDelete.setForeground(new java.awt.Color(255, 255, 255));
    btnDelete.setText("Delete");
    btnDelete.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnDeleteActionPerformed(evt);
      }
    });

    btnCreate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    btnCreate.setText("Create");
    btnCreate.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCreateActionPerformed(evt);
      }
    });

    btnUpdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    btnUpdate.setText("Update");
    btnUpdate.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnUpdateActionPerformed(evt);
      }
    });

    tblPeople.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {

      }
    ));
    tblPeople.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    tblPeople.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        tblPeopleMouseReleased(evt);
      }
    });
    spTblPeople.setViewportView(tblPeople);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(spTblPeople)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(lblFName)
                  .addComponent(lblLName)
                  .addComponent(tfLName)
                  .addComponent(tfFName, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 977, Short.MAX_VALUE)))
            .addContainerGap())))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(18, 18, 18)
        .addComponent(lblFName)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(tfFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(lblLName)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(tfLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(spTblPeople, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

  private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
    try {
      this.init();
    }
    catch (Exception ex) {
      Messages.showErrorMessage("Error occured", ex.getMessage());
      Logger
        .getLogger(PersonCRUDView.class.getName())
        .log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_formComponentShown

  private void tblPeopleMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPeopleMouseReleased
    try {
      this.cleanValidationFields();
      this.showSelectedPerson();
    }
    catch (Exception ex) {
      Messages.showErrorMessage("Error occured", ex.getMessage());
      Logger
        .getLogger(PersonCRUDView.class.getName())
        .log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_tblPeopleMouseReleased

  private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
    if (!this.isFormValid())
      return;

    try {
      Optional<PersonDomainModel> person =
                                  this._personManager.add(new PersonDomainModel(
                                    tfFName.getText().trim(),
                                    tfLName.getText().trim()));

      if (person.isEmpty()) {
        Messages.showErrorMessage("Person already exists",
                                  "Please insert valid unique first name and last name.");
        return;
      }

      this.init();

    }
    catch (Exception ex) {
      Messages.showErrorMessage("Error occured", ex.getMessage());
      Logger.getLogger(PersonCRUDView.class.getName()).log(Level.SEVERE, null,
                                                           ex);
    }
  }//GEN-LAST:event_btnCreateActionPerformed

  private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
    if (this._selectedPerson.isEmpty() || !this.isFormValid())
      return;

    try {
      int updatedCount =
          this._personManager.edit(this._selectedPerson.get().getGuid(),
                                   new PersonDomainModel(
                                     tfFName.getText().trim(),
                                     tfLName.getText().trim()));

      if (updatedCount == 0) {
        Messages.showErrorMessage("Person already exists",
                                  "Please insert valid unique first name and last name.");
        return;
      }

      this.init();

    }
    catch (Exception ex) {
      Messages.showErrorMessage("Error occured", ex.getMessage());
      Logger.getLogger(PersonCRUDView.class.getName()).log(Level.SEVERE, null,
                                                           ex);
    }
  }//GEN-LAST:event_btnUpdateActionPerformed

  private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       if (this._selectedPerson.isEmpty())
      return;

    int dialogResult = Messages.showConfirmDialog(
        "Do you really want to delete person?",
        "Deleted person can be returned only by application admin.");
    if (dialogResult != JOptionPane.OK_OPTION)
      return;

    try {
      int removeCount = this._personManager.remove(this._selectedPerson.get()
          .getGuid());

      if (removeCount == 0) {
        Messages.showErrorMessage("Person was not deleted",
                                  "Problem occured while deleting person.");
        return;
      }

      Messages.showInformationMessage("Person was deleted",
                                      "Person was successfully deleted.");
      this.init();
    }
    catch (Exception ex) {
      Messages.showErrorMessage("Error occured", ex.getMessage());
      Logger
        .getLogger(PersonCRUDView.class.getName())
        .log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_btnDeleteActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCreate;
  private javax.swing.JButton btnDelete;
  private javax.swing.JButton btnUpdate;
  private javax.swing.JLabel lblFName;
  private javax.swing.JLabel lblLName;
  private javax.swing.JScrollPane spTblPeople;
  private javax.swing.JTable tblPeople;
  private javax.swing.JTextField tfFName;
  private javax.swing.JTextField tfLName;
  // End of variables declaration//GEN-END:variables

  private void init()
    throws Exception {
    this.defaultValidationFieldBorders();
    this.cleanValidationFields();
    this.initTable();
  }

  private void initTable()
    throws Exception {
    tblPeople.setAutoCreateRowSorter(true);
    tblPeople.setMaximumSize(new Dimension(spTblPeople.getWidth(),
                                           spTblPeople.getHeight()));

    Collection<PersonDomainModel> people =
                                  _personManager.getAllIfAvailable();
    var tableModel = new PersonTableModel((List<PersonDomainModel>) people);
    tblPeople.setModel(tableModel);
  }

  private void showSelectedPerson()
    throws Exception {
    int selectedRow = tblPeople.getSelectedRow();
    int realRowIndex = tblPeople.convertRowIndexToModel(selectedRow);
    int keyOfRow =
        ((PersonTableModel) tblPeople.getModel()).getKeyOfRow(realRowIndex);

    this._selectedPerson = this._personManager.getByIdIfAvailable(keyOfRow);
    if (this._selectedPerson.isPresent())
      fillForm(this._selectedPerson.get());
  }

  private void cleanValidationFields() {
    this._validationFields.forEach(field -> field.setText(""));
  }

  private void fillForm(PersonDomainModel person) {
    this.tfFName.setText(person.getFName());
    this.tfLName.setText(person.getLName());
  }

  private boolean isFormValid() {
    boolean ok = true;

    for (JTextField field : this._validationFields) {
      String text = field.getText().trim();
      ok &= !text.isEmpty();

      if (text.isEmpty())
        Borders.setBorderError(field);
      else
        Borders.setBorderDefault(field);
    }

    return ok;
  }

  private void defaultValidationFieldBorders() {
    this._validationFields.forEach(field -> Borders.setBorderDefault(field));
  }

}
